//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlojPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.PrijavaTakmicara = new HashSet<PrijavaTakmicara>();
        }
    
        public int KorisnikID { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public string ImePrezimeTrenera { get; set; }
        public string NazivKluba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrijavaTakmicara> PrijavaTakmicara { get; set; }
    }
}
