//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlojPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrijavaTakmicara
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrijavaTakmicara()
        {
            this.StavkaPrijave = new HashSet<StavkaPrijave>();
        }
    
        public int PrijavaID { get; set; }
        public string NazivPrvenstva { get; set; }
        public string Disciplinam { get; set; }
        public System.DateTime DatumPrijave { get; set; }
        public string Mesto { get; set; }
        public int KorisnikID { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaPrijave> StavkaPrijave { get; set; }
    }
}
