//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlojPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class StarosnaKategorija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StarosnaKategorija()
        {
            this.StavkaPrijave = new HashSet<StavkaPrijave>();
        }
    
        public int KategorijaID { get; set; }
        public string NazivKategorije { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaPrijave> StavkaPrijave { get; set; }
    }
}
