//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlojPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaPrijave
    {
        public int StavkaID { get; set; }
        public int PrijavaID { get; set; }
        public string ImePrezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public int KategorijaID { get; set; }
        public string TezinskaKategorija { get; set; }
    
        public virtual PrijavaTakmicara PrijavaTakmicara { get; set; }
        public virtual StarosnaKategorija StarosnaKategorija { get; set; }
    }
}
