//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlojPodataka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TakmicenjeDBEntities2 : DbContext
    {
        public TakmicenjeDBEntities2()
            : base("name=TakmicenjeDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<PrijavaTakmicara> PrijavaTakmicara { get; set; }
        public virtual DbSet<StarosnaKategorija> StarosnaKategorija { get; set; }
        public virtual DbSet<StavkaPrijave> StavkaPrijave { get; set; }
    
        public virtual ObjectResult<sp_ProveriKorisnika_Result> sp_ProveriKorisnika(string korisnickoIme, string lozinka)
        {
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaParameter = lozinka != null ?
                new ObjectParameter("Lozinka", lozinka) :
                new ObjectParameter("Lozinka", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ProveriKorisnika_Result>("sp_ProveriKorisnika", korisnickoImeParameter, lozinkaParameter);
        }
    
        public virtual int sp_UnesiPrijavu(string nazivPrvenstva, string disciplinam, string mesto, Nullable<int> korisnikID, ObjectParameter prijavaID)
        {
            var nazivPrvenstvaParameter = nazivPrvenstva != null ?
                new ObjectParameter("NazivPrvenstva", nazivPrvenstva) :
                new ObjectParameter("NazivPrvenstva", typeof(string));
    
            var disciplinamParameter = disciplinam != null ?
                new ObjectParameter("Disciplinam", disciplinam) :
                new ObjectParameter("Disciplinam", typeof(string));
    
            var mestoParameter = mesto != null ?
                new ObjectParameter("Mesto", mesto) :
                new ObjectParameter("Mesto", typeof(string));
    
            var korisnikIDParameter = korisnikID.HasValue ?
                new ObjectParameter("KorisnikID", korisnikID) :
                new ObjectParameter("KorisnikID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UnesiPrijavu", nazivPrvenstvaParameter, disciplinamParameter, mestoParameter, korisnikIDParameter, prijavaID);
        }
    
        public virtual int sp_UnesiStavkuPrijave(Nullable<int> prijavaID, string imePrezime, Nullable<System.DateTime> datumRodjenja, Nullable<int> kategorijaID, string tezinskaKategorija)
        {
            var prijavaIDParameter = prijavaID.HasValue ?
                new ObjectParameter("PrijavaID", prijavaID) :
                new ObjectParameter("PrijavaID", typeof(int));
    
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            var datumRodjenjaParameter = datumRodjenja.HasValue ?
                new ObjectParameter("DatumRodjenja", datumRodjenja) :
                new ObjectParameter("DatumRodjenja", typeof(System.DateTime));
    
            var kategorijaIDParameter = kategorijaID.HasValue ?
                new ObjectParameter("KategorijaID", kategorijaID) :
                new ObjectParameter("KategorijaID", typeof(int));
    
            var tezinskaKategorijaParameter = tezinskaKategorija != null ?
                new ObjectParameter("TezinskaKategorija", tezinskaKategorija) :
                new ObjectParameter("TezinskaKategorija", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UnesiStavkuPrijave", prijavaIDParameter, imePrezimeParameter, datumRodjenjaParameter, kategorijaIDParameter, tezinskaKategorijaParameter);
        }
    }
}
